### ISSUE TITLE
Repeats API call 5x on every press

### ISSUE THREAD

**Issue by steubens** [danimtb/dasshio#10]
Hi, there is an issue where this addon repeats the API call 5x for every button press.  I have tried forking the repo and changing the wait value to 60 seconds, 300 seconds, and 1 second.  no matter what, it just waits X seconds and repeats until it has called the API 5x... I don't know enough to troubleshoot further.  Hopefully, you can take a look at this and help fix it?  thx!

Logs (1 second delay in place):
```
root@hassio:~# docker logs -f 9cc5e9e13520
starting version 3.2.2
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
2017-10-31 23:36:38,327 | INFO | Reading config file: /data/options.json
2017-10-31 23:36:38,329 | INFO | Starting sniffing...
2017-10-31 23:37:02,977 | INFO | ziplock button pressed!
2017-10-31 23:37:02,978 | INFO | Request: http://x.x.x.x:8123/api/services/script/dash_ziplock
2017-10-31 23:37:03,426 | INFO | Status Code: 200
2017-10-31 23:37:03,427 | INFO | Successful request
2017-10-31 23:37:04,439 | INFO | ziplock button pressed!
2017-10-31 23:37:04,440 | INFO | Request: http://x.x.x.x:8123/api/services/script/dash_ziplock
2017-10-31 23:37:04,868 | INFO | Status Code: 200
2017-10-31 23:37:04,869 | INFO | Successful request
2017-10-31 23:37:05,881 | INFO | ziplock button pressed!
2017-10-31 23:37:05,882 | INFO | Request: http://x.x.x.x:8123/api/services/script/dash_ziplock
2017-10-31 23:37:06,302 | INFO | Status Code: 200
2017-10-31 23:37:06,303 | INFO | Successful request
2017-10-31 23:37:07,315 | INFO | ziplock button pressed!
2017-10-31 23:37:07,316 | INFO | Request: http://x.x.x.x:8123/api/services/script/dash_ziplock
2017-10-31 23:37:07,740 | INFO | Status Code: 200
2017-10-31 23:37:07,742 | INFO | Successful request
2017-10-31 23:37:08,755 | INFO | ziplock button pressed!
2017-10-31 23:37:08,756 | INFO | Request: http://x.x.x.x:8123/api/services/script/dash_ziplock
2017-10-31 23:37:09,266 | INFO | Status Code: 200
2017-10-31 23:37:09,267 | INFO | Successful request
```

**Comment by danimtb** [comment]
Hi @someinternetguy!

You are right. This is a known issue tha tI have not been able to solve yet. I tried to fix it with the delays between each API call but it didnt work.

I have experienced it is more likely to happen if your home asisstance instance is communicating over wifi. However it may also happen with a wired connection.

My guess is that this has something to do with container networking and the scapy python library. Unfortunately I haven't found any fix yet.

I will keep this issue open until it is solved. Thanks for reporting!

**Comment by steubens** [comment]
@danimtb thanks for the reply.  and thanks for the addon, even with the repeat issue, it still works and I'm using it to call a script!

**Comment by PaulFinch** [comment]
A bit annoying when you use a toggle command ...
Did someone try to increase the sleep value here ?
```
 finally:
                time.sleep(20) # Wait 20 seconds to let dash button disconnect from wifi before scanning again
```

**Comment by steubens** [comment]
@PaulFinch, yes. see my original comment.  I called it "wait" but I should have said "sleep value".  I've tried @ 2, 20 (default), and 300... its just waits the sleepvalue and repeats 5x, waiting sleep value between each iteration.

**Comment by PaulFinch** [comment]
OK, wasn't sure where you placed the sleep. Then it must be related to the sniff function. Actually this was working not so long ago (~1month: version 0.0.7). Mine is repeating only twice.

From 0.0.7 to 0.0.8, this changed : 
```
-sniff(prn=arp_display, filter='arp', store=0, count=0)
 +sniff(prn=arp_display, filter='(arp or (udp and src port 68 and dst port 67)) and src host 0.0.0.0', store=0, count=0)
```
Is it possible that the sniff function captures both **arp** AND **udp** packets ?

The other possibility (which would describe the best the issue here) is that the loop inside the function run for every configured button (I don't know why it would do that), just to be sure **someinternetguy** , how many buttons did you configure ? 
```
for button in config['buttons']:
        if mac == button['address'].lower() and guard[button['address']] == False:
```

Unfortunately, I'm not familiar with docker env enough to make some tests directly on hassio

**Comment by PaulFinch** [comment]
I made some tests (not on hassio), it does not come from the 2 assumptions i made before.
This looks like to come from the scapy/sniff function

**Comment by danimtb** [comment]
If you run the python script out of the docker container it should work
properly (one api call per press). However, when running on hassio I get 2
api calls if rpi connected by ethernet and 5 or 4 when connected over wifi.

The change in the sniff function worked the same for me. That's why I think
this might be related to networking of the scapy library inside containers.

**Comment by PaulFinch** [comment]
I will describe what happen here, I have 2 calls, sometime only 1. It is the dhcp requests ! Sometimes 2 sometimes 1 ... or maybe more ...

it is because the sniff function is not async, it seems to be like a queue,  each  function call waiting the previous one to finish (so in that case the guard seems to be useless).

So in that case I should have 3 calls (2 DHCP requests + ARP request).
It is because it appeared to me that the filter is not correct, 
`filter='(arp or (udp and src port 68 and dst port 67)) and src host 0.0.0.0'`
because this filter does not capture any arp packet, it should be instead 
`filter='arp or (udp and src port 68 and dst port 67 and src host 0.0.0.0')`

But to me, it would be better to ditch the udp thing and only use the arp ...
We didn't have the problem because only 1 arp request is sent.

**Comment by danimtb** [comment]
Have you tried just setting the filter back to 'arp'?

**Comment by PaulFinch** [comment]
yep, if you filter only on arp it works as expected (only one call).
the problem with udp 68/67 is that you can have several DHCP requests.

**Comment by danimtb** [comment]
Ok, I will revert the addon to just arp packets. But we will still have the
same issue (double api call) inside the container.

**Comment by PaulFinch** [comment]
i guess the question is, why was it (udp stuff) implemented ? 
Why do you think we'll have the same issue ?

I tested a personal version of this script [Here](https://github.com/PaulFinch/hassio-addons/blob/master/dasshio/dasshio.py)
Works well for me but maybe it depends on the dash button version or users environments.

just if you want the tip, I removed the scapy IPv6 warnings by adding this line between the logging import and the scapy imports : 
`logging.getLogger("scapy.runtime").setLevel(logging.ERROR)`

**Comment by danimtb** [comment]
Hi @PaulFinch,

UDP stuff was implemented in order to support Dash Buttons V2, However I think it also works with teh filter set to 'arp'.

I will try to revert some changes to see if works. Thanks for the tip.

**Comment by danimtb** [comment]
Maybe something like this could work:

https://stackoverflow.com/questions/28846766/python-stop-sniffing-upon-specific-condition

Stop sniff after detecting button press and then resume it after some seconds

**Comment by PaulFinch** [comment]
I confirm, I have a dash v2, arp still works. i guess the udp dhcp request detection is faster than the arp. 

Your idea is good, it could be possible to create a loop to sniff with a stop_filter activated when the button is pressed. Then sleep x seconds, and sniff again ... 

()to work with infinite loops, it is better to implement a SIG_TERM/SIG_KILL handle function)

**Comment by PaulFinch** [comment]
Tested [Here](https://github.com/PaulFinch/hassio-addons/blob/master/dasshio/dasshio.py)

**Comment by danimtb** [comment]
@PaulFinch nice work!

Have you tested it inside teh docker image in hassio?
Is that working fine?

**Comment by PaulFinch** [comment]
yes i did, no problem so far ...
You can test it as well with my repository. I changed the addon name so both yours and mine can be installed at the same time. Just stop the other addon when testing.

The only drawback is, when a button is pressed, you can't use the dash button again for 30s, even with another dash button ... (We could use Threads for that but it will become quite complex ^)

**Comment by PaulFinch** [comment]
I did it ... [Here](https://github.com/PaulFinch/hassio-addons/blob/master/dasshio/dasshio.multiprocessed.py)

Each configured button runs a new process listening only on the src mac of the button, this way you don't have the previously explained drawback.

Even if it works well, I wouldn't advice to deploy this, multiprocessing is hard to control. it was just for fun actually ...

Edit : Actually this works pretty good.

**Comment by danimtb** [comment]
Hey @PaulFinch,
Thank you so much for your development.
I would like to update dasshio to use the stop function with the while loop

Could you please contribute and make a PR with you changes?

**Comment by PaulFinch** [comment]
Sure, I will (in the dev branch i guess)

**Comment by danimtb** [comment]
Yes, devel branch. Thank you

I try to keep master untouched until release. Otherwise, people using the addon for the 1st time will get a develop version. Moreover, this way Hassio users dont get the update notification until new version is ready.

**Comment by steubens** [comment]
Thanks both for looking into, and fixing this!!  Sorry, I couldn't be of more help than just complaining about the issue...

**Comment by PaulFinch** [comment]
Done

**Comment by danimtb** [comment]
Merged to master and issue solved.
Thanks @someinternetguy for reporting and @PaulFinch for the fix!! 🥇
