### ISSUE TITLE
support for 'dash wand'?

### ISSUE THREAD

**Issue by sebaschn** [danimtb/dasshio#109]
hello there,

i've been using the dash buttons in my brand new HA setup for a few weeks now.
then i've learned about the dash wand, bought one on ebay but had no success with the provided config URL, youve posted here:
`http://192.168.0.1/?amzn_ssid=<SSID>&amzn_pw=<PASSWORD>`

google also has no clue.

could anyony lead my in the right direction?
is this a future feature maybe?

**Comment by danimtb** [comment]
Sorry, this has nothing to do with the dash wand, it was only intended to support amazon's dash buttons
