### ISSUE TITLE
Where to put the config file ?

### ISSUE THREAD

**Issue by vincegre** [danimtb/dasshio#111]
Hi

I have installed it easily in Hassio but I'm quite confused where to put the /data/options.json as I have no data directory in all hassio directories visible through samba share :(

Thanks for clarification ;)

Vincèn

**Comment by brucemiranda** [comment]
I believe the options.json gets created automatically with the configuration data that you enter via the add-on configuration UI. You don't create that file yourself.

**Comment by vincegre** [comment]
> I believe the options.json gets created automatically with the configuration data that you enter via the add-on configuration UI. You don't create that file yourself.

Thanks but I have given up since a long time on these devices ;) I'll close that ticket !
