### ISSUE TITLE
Service started but not responding to Dash buttons

### ISSUE THREAD

**Issue by manda-iow** [danimtb/dasshio#114]
I have a very new install of Hassio from the Raspberry Pi 'Home Assistant Operating System' image. I have the Dasshio add-on installed and it starts up with no issues. The log reports:
<img width="439" alt="image" src="https://github.com/danimtb/dasshio/assets/144139234/1d8a36ac-ecaf-472a-9be2-31f966102f3b">
so I have no reason to suspect config issues. My config shows:
<img width="399" alt="image" src="https://github.com/danimtb/dasshio/assets/144139234/af25c6b8-255f-48bb-a7b5-a274bfad32d8">
However nothing happens on button press, the log stays the sames, it's like the button isn't being acknowledged at all.

I have tried multiple buttons and I know the buttons work as I have used https://github.com/Nekmo/amazon-dash on a different Pi instance to good effect. I did have to tweak my base Pi OS with some networking changes to get this to work so I'm wondering if there is something more I need to do in my hassio instance to get the networking side working?

Apologies but this *IS* my first rodeo :) and I'm unclear what to do or how to troubleshoot. I have access to the CLI but wouldn't know what to do there. It feels like because I've used the stock image for hassio I'm missing a few dependencies which more advanced docker peeps will have...any thoughts?

**Comment by githubuser100000000** [comment]
same here!!!

**Comment by manda-iow** [comment]
Out of interest, are you using HASSIO and is it running on a PI3 or PI4?
    On Wednesday, 18 October 2023 at 22:39:39 BST, githubuser100000000 ***@***.***> wrote:  
 
 


same here!!!

**Comment by alexalex89** [comment]
Have you tried replacing the dashes in the MAC with colons?

**Comment by manda-iow** [comment]
> Have you tried replacing the dashes in the MAC with colons?

Sometimes it just needs someone to state the blindingly obvious! Thank you very much for pulling me out of my deep hole of second guessing 50 million complex things and forgetting to even check the simple things - too much remote working and no one to bounce stuff off :(
Yeah, I copy/pasted the MAC address straight from the Dash config page never giving the delimiters a second thought!
Now where was I with all my smart home plans...thanks again for giving my project a whole new lease of life for 2024! 👍🏻

**Comment by alexalex89** [comment]
> thanks again for giving my project a whole new lease of life for 2024! 👍🏻

You're welcome :D
