### ISSUE TITLE
Add MQTT support?

### ISSUE THREAD

**Issue by LimeBlast** [danimtb/dasshio#19]
I love this, it's almost exactly what I was looking for. If I could offer some feature suggestion, however, it would be to add some MQTT support.

I'm still new to HA and MQTT in general, but if it was possible to specify the broker, the topic and the message to be sent, all within the config json, that would be awesome, and go a long way towards what I'm hoping to achieve with the system.

Thank you :)

**Comment by danimtb** [comment]
Hi @LimeBlast!

Thank you for your suggestion.

Have you tried using the mqtt service?

```
{
  "buttons": [
  {
    "name": "Gillette",
    "address": "AC:63:BE:77:C4:0D",
    "url": "http://homeassistant:8123/api/services/mqtt/publish",
    "headers": "{\"x-ha-access\": \"your_password\"}",
    "body": "{\"topic\": \"/your/mqtt/topic\",\"payload\":\"ON\"}"
  }
}
```

This way you would make Home Assistant publish "ON" to the "/your/mqtt/topic" topic

**Comment by LimeBlast** [comment]
I hadn't, but I don't see why that wouldn't work. Thank you :)
