### ISSUE TITLE
Dasshio broken in 65.0.

### ISSUE THREAD

**Issue by mattlward** [danimtb/dasshio#29]
This config worked perfectly in 64.3 and never registers a button press in 65.0.
I have done a rebuild, stop and start, but not an uninstall yet.  Log looks good for dasshio.

Maybe the new entity ID stuff?
```
starting version 3.2.4
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
2018-03-10 18:15:55,107 | INFO | Reading config file: /data/options.json
2018-03-10 18:15:55,113 | INFO | Starting sniffing...
```
```
{
  "timeout": 8,
  "buttons": [
    {
      "name": "Hammermill",
      "address": "00:fc:8b:54:41:d9",
      "domain": "light",
      "service": "toggle",
      "service_data": "{\"entity_id\": \"light.bathroom_2, light.bathroom_1\"}"
    }
  ]
}
```

**Comment by mattlward** [comment]
I am beginning to think the button died!  I can't get into the web page and it only gives a faint blue light and then red flashes.

**Comment by AlexCalderon02** [comment]
Matt, you can check the battery status by holding the button for ~10 seconds until it flashes blue. You can then connect to it via wifi on your windows or linux machine. After connecting to the dash via wifi, head to your browser and type "192.168.0.1" and there should be wifi. Address like localhost or 127.0.0.1 will also work

**Comment by mattlward** [comment]
Ah, I had found that I needed to browse to a different IP address after connecting.  Will try that.  But, none the less it does not work after 65.0.  I assume the button died, but could be wrong.

**Comment by danimtb** [comment]
Did you have the time to check if the button was dead? Are you still having issues with Dasshio @mattlward ?

**Comment by danimtb** [comment]
Any update on this @mattlward ?

**Comment by mattlward** [comment]
Yes.  Dash button quit, replaced with xaiomi and have not looked back.

**Comment by danimtb** [comment]
Fine, thanks for writing back. Closing this
