### ISSUE TITLE
Cannot install add-on in hass.io

### ISSUE THREAD

**Issue by sccsltd** [danimtb/dasshio#30]
Hass.io installed in docker on Ubuntu 16.04.4.
Home assistant 65.5
hass.io supervisor 0.98

try to install via addon store and get the following error. 

18-03-15 21:57:34 INFO (SyncWorker_5) [hassio.docker.addon] Start build 03d23610/amd64-addon-dasshio:0.2.1
18-03-15 21:57:34 ERROR (SyncWorker_5) [hassio.docker.addon] Can't build 03d23610/amd64-addon-dasshio:0.2.1: Please provide a source image with `from` prior to commit

**Comment by ian-tait** [comment]
I'm getting the same issue with the same versions.

**Comment by ian-tait** [comment]
Has anyone got a solution to this issue?
I would really like to see this working with my HA.

**Comment by sccsltd** [comment]
dont really understand how the addon system works.. but i cloned the repo to have a play and i have it installed now. will test the functionality shortly. i can only assume there is an issue with docker versions or something because  i cannot see a diffeence between the docker file for this addon to all the others, 

however putting the from first and specifying the build as amd_64 seems to work.

Ian-Tait feel free to use my test repo untill the author has a chance to look at it for us.
https://github.com/sccsltd/DashBtn 

unsure how the whole github forking branging etc works so i just downloaded this and reuploaded it to my repo.

**Comment by ian-tait** [comment]
sccsltd, I have to say for someone who claims not to know what your doing, that worked perfectly.
Thank you for your support. 

I will keep an eye out for when this is fixed and will switch back then.

**Comment by iantrich** [comment]
I was able to install by adding the repo and installing like a normal add-on without issue.

Hass.io installed in docker on Ubuntu Server 17.10.4.
Home assistant 67.1
hass.io supervisor 0.101

**Comment by danimtb** [comment]
Thanks for the feedback @iantrich !

I think I would add the build file from @sccsltd repo https://github.com/sccsltd/DashBtn/blob/master/dashino/build.json that seems to be the only difference. Is that right?

I would release a new dasshio version if that solves the issue.

**Comment by mealan** [comment]
sadly this other repo doesn't work for me for 68.1, ubuntu 16.4 lts, and hass.io supervisor 0.101

**Comment by danimtb** [comment]
any update on this? could you help to fix this issue @sccsltd @ian-tait?

Is the *build.json* the only change needed to make dasshio work?

**Comment by schmurtzm** [comment]
I just tried sccsltd repo on hass.io 103.2 (docker on ubuntu), it's not working anymore

**Comment by danimtb** [comment]
OK @schmurtzm, thanks for reporting. I will check in my instance after the update

**Comment by schmurtzm** [comment]
Just tried on a raspberry (still hass.io 103.2) : no problem it works fine.
In fact there are so much add-ons that no works correctly on ubuntu with docker...

Spotify -> not working
homebridge -> not working
dasshio -> impossible to install
MQTT -> not working
sonos album jackets -> working in a strange way

...and no problem with all these add-ons on a raspberry... So I really recommand to use raspberry.
Slower and more expensive than my ubuntu VM but it's working without problems...

**Comment by davemuench** [comment]
For what it's worth - I run hass.io on an ubuntu VM, and both dasshio and the MQTT addons work fine. So do all the other ones I use - node-red, appdaemon3, git pull, and check config. There might be something else odd going on with your install.

**Comment by mealan** [comment]
and dashio and home bridge are working for me in a vm

**Comment by schmurtzm** [comment]
Ok I reinstall hass.io on a fresh ubuntu, it's better for many add-ons but dasshio still not want to be installed.
Is there a way to install it manually ?
davemuench & mealan -> how have you installed dasshio ? May be you have installed it on an old version of hass.io ?

**Comment by davemuench** [comment]
In the normal way, via the hassio add ons store page in the GUI. I installed it probably 6 months ago, and have kept it up to date since.

**Comment by schmurtzm** [comment]
After a new reinstall in the right way it's working correctly on VMware Player with Ubuntu 18 server and hass.io 0.72.0.
I follow this tutorial to install : 
https://github.com/home-assistant/hassio-build/tree/master/install#install-hassio
I'm pretty sure that the problem comes from others kind of installation.

**Comment by danimtb** [comment]
I have just released 0.3.0 version of dasshio with new build images uploaded to dockerhub, so this should not be an issue any more. Please update!
