### ISSUE TITLE
Cannot use tts successfully.

### ISSUE THREAD

**Issue by kikura** [danimtb/dasshio#31]
Hi,

I hope you can help. I am trying to use the Dash button as a doorbell so that my Google home speakers say "Someone is at the door" when it is pressed.

I have successfully set it up to control a smart bulb but the doorbell setup will not work.

My Dashio config looks like this:

{
  "timeout": 20,
  "buttons": [
    {
      "name": "Doorbell",
      "address": "XX:XX:XX:XX:XX:XX",
      "domain": "media_player",
      "service": "tts.google_say",
      "service_data": "{\"entity_id\": \"media_player.downstairs\", \"message\": \"'someones at the door'\"}"
    }
  ]
}

And the log when I press the button reads:

Log
starting version 3.2.4
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
2018-03-22 18:48:19,912 | INFO | Reading config file: /data/options.json
2018-03-22 18:48:19,922 | INFO | Starting sniffing...
2018-03-22 18:48:23,523 | INFO | Doorbell button pressed!
2018-03-22 18:48:23,526 | INFO | Request: http://hassio/homeassistant/api/services/media_player/tts.google_say

So it recognised the button press and there are no errors generated, but nothing come out of the speakers. TTS seems to work fine through the media player widgets on the overview page of Home Assistant.

Any help would be much appreciated.

Nick.

Edit: masked MAC address.

**Comment by danimtb** [comment]
Hi @kikura!

Seems you dasshio json configuration is wrong.

As the field **service_data** uses json format, and Hassio addons do not support more than two nested arrays in json (see [warning in the readme](https://github.com/danimtb/dasshio#options-example-domain-service-service_data)), you have to scape " like this -> \\"

This should be your right config:
```
{
  "timeout": 20,
  "buttons": [
    {
      "name": "Doorbell",
      "address": "B4:7C:9C:F9:27:E1",
      "domain": "media_player",
      "service": "tts.google_say",
      "service_data": "{\"entity_id\": \"media_player.downstairs\", \"message\": \"someones at the door\"}"
    }
  ]
}
```

**Comment by kikura** [comment]
Apologies, but in the original file the escape characters were there, they just didn't copy and paste correctly onto this page.

Nevertheless, I have cut and pasted your config from above and it still doesn't work.

**Comment by danimtb** [comment]
Could you post here versions of hassio, hass and dasshio?

Have you checked that you can call that service from the service tab in your home asssitant? Is that working?

**Comment by kikura** [comment]
Hi. 

Many thanks for your help. After some messing around, I discovered that in my config above, domain should be "tts" and service should be "google_say".

Nick

**Comment by danimtb** [comment]
You are welcome 😄 Please feel free to close this issue if it is working now with dasshio 😉
