### ISSUE TITLE
Dashio not working after upgrading Hassio 0.68.1

### ISSUE THREAD

**Issue by cryptooth** [danimtb/dasshio#32]
Here is the log:

> 2018-05-06 10:37:37,448 | INFO | Mutfak button pressed!
> 2018-05-06 10:37:37,450 | INFO | Request: http://hassio/homeassistant/api/services/switch/toggle
> 2018-05-06 10:37:37,498 | INFO | Status Code: 500
> 2018-05-06 10:37:37,499 | ERROR | Bad request
> 2018-05-06 10:37:37,563 | INFO | Packet captured, waiting 10s ...
> 2018-05-06 10:37:47,572 | INFO | Starting sniffing...

hassio => 0.68.1
supervisor => 103.1

**Comment by cryptooth** [comment]
Problem solved after chaning the config like:

from:
```
{
    "name": "Gillette",
    "address": "AC:63:BE:77:C4:0D",
    "domain": "light",
    "service": "toggle",
    "service_data": "{\"entity_id\": \"light.room_light\"}"
  },

```
to

```
  {
      "name": "Gillette",
      "address": "**:**:**:**:**:ea",
      "url": "http://homeassistant:8123/api/services/light/toggle",
      "headers": "{\"x-ha-access\": \"*******\"}",
      "body": "{\"entity_id\": \"light.abatjour\"}"
    },
```

**Comment by danimtb** [comment]
HI @cryptooth 
I dont know why the first config is not working... I see some changes from your first commet to the second one.

In the first one you are using a switch toggle and in thes econd onea light toggle. Maybe that was the issue.

So the log of he first comment does not mathc the "from" configuration you posted:

> {
>     "name": "Gillette",
>     "address": "AC:63:BE:77:C4:0D",
>     "domain": "light",
>     "service": "toggle",
>     "service_data": "{\"entity_id\": \"light.room_light\"}"
>   },

**Comment by davemuench** [comment]
FWIW, this happened to me last night as well. I am running hassio 0.67.1 and this didn't coincide with me upgrading. Restarted the dashio container and it didn't help. Today it works again. I didn't make any configuration changes to dashio or hass since last night. Very strange.

**Comment by danimtb** [comment]
Thanks for commenting @davemuench. I hace to check dasshio with the new update and see what is going on
