### ISSUE TITLE
Any way to stop the "Your dash button is almost ready" notification? 

### ISSUE THREAD

**Issue by SurfingSpider** [danimtb/dasshio#33]
Is there any way to stop the "Your dash button is almost ready" notification on your phone without turning off all amazon notifications? I dont suppose there is

P.S. thanks for such an easy to use addon, the other methods I looked at to get a dash button working seamed lots more complicated. I found it super simple to setup (can I give a bit of feedback on the readme notes. I did spend a while trying to edit the /data/options.json file until I realised the config is done in the addon config within HASSIO you dont have to ssh into the pi to edit the file). 

Many Thanks

**Comment by danimtb** [comment]
Hi @SurfingSpider 
Wow, thanks a lot for the great feedback! I am glad many users are finding this addon useful 😄 

Regarding the notification, I know two approaches to this:
1. Disable notifiaction of dash buttons in amazon app: Account -> Dash devices: Manage devices -> Notifications settings.
2. Block internet access to a dash button inside your router: Go to the settings of your router and block the access to internet to the MAC of your dash device.

I have tried first approach and it works well. However I only use dash buttons with home assistant, so if you use any of them to actually order things from amazon maybe you can miss any notification.

The second approach can avoid the issue described in the first one. However, some people say the dash button stays awake more time, which may cause some trouble with dasshio triggering more than once and will definitely make the device run out of battery earlier. I dont know if this is true or not, I have not tried myself.

Please, feel free to open a Pull Request adding any useful information to the readme. Maybe it would be useful to have a kind of FAQ section with this information too.

Thanks!

**Comment by danimtb** [comment]
@SurfingSpider did you found and answer in the information provided? If not please ask any doubt you may have or post your final solution so we all can learn. I fhte issue is solved then please feel free to close it! Thanks 😄

**Comment by SurfingSpider** [comment]
I turned off dash notifications in the amazon app.

settings > notifications > dash button updates

**Comment by danimtb** [comment]
Great @SurfingSpider! thanks a lot for sharing yopur solution. Do not hesitate to report any other issue or question 😄
