### ISSUE TITLE
ModuleNotFoundError: No module named 'scapy'

### ISSUE THREAD

**Issue by NickChamberlin** [danimtb/dasshio#35]
I recently started fresh with hassio and installed dasshio again. Before I started fresh I had dasshio working with hassio.

this is the log:

```
Traceback (most recent call last):
  File "dasshio.py", line 7, in <module>
    from scapy.all import sniff
ModuleNotFoundError: No module named 'scapy'
```
dasshio does not start when I reboot hassio, even though start on boot is enabled. I have to manually start the add-on.

this is my config in the dasshio add-on:

```
{
  "timeout": 8,
  "buttons": [
    {
      "name": "test",
      "address": "fc:65:de:ca:a3:8d",
      "domain": "light",
      "service": "toggle",
      "service_data": "{\"entity_id\": \"light.bedroom\"}"
    }
  ]
}
```

The dash button is connecting to my wifi, but dasshio isn’t working.

hassio ver: 0.69.1
dasshio ver: 0.2.1

tried rebuilding dasshio, restarting, uninstalling dasshio and reinstalling.
dasshio keeps disabling itself.

**Comment by EGP01** [comment]
I have exactly the same problem. I changed what I wanted the button to do light to running a script. Hit rebuild and it no longer works. Have tried same as you including removing the repository. Shame was working a treat up till now

**Comment by vicky4050** [comment]
Seems like there is a new version of scapy.

You can host the Addon Locally (https://developers.home-assistant.io/docs/en/hassio_addon_tutorial.html)

And edit the  requirements.txt to  force install the prev version "scapy-python3==0.23". 

Works for me.

The version history:
https://pypi.org/project/scapy-python3/#history

**Comment by danimtb** [comment]
Thanks @vicky4050 for the info! I will update ASAP and release a new version of dasshio

**Comment by gpotter2** [comment]
Watch out,
`scapy-python3` is super outdated, and an unofficial fork of scapy.
Scapy>=2.4.0 has full python 3 support

Better fix in https://github.com/danimtb/dasshio/pull/36

**Comment by danimtb** [comment]
agree, thanks @gpotter2

**Comment by danimtb** [comment]
Merged!
