### ISSUE TITLE
FileNotFoundError Error - Permissions

### ISSUE THREAD

**Issue by noloco** [danimtb/dasshio#37]
When trying to install, I'm getting a permissions file write error:
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']

This issue looks very similar to a Node-Red issue:
https://community.home-assistant.io/t/cant-install-node-red-hass-io-ubuntu-18-04/53286/3

Wondering if it requires the same fix?

**Comment by danimtb** [comment]
Seems a problem in the hassio add-on installer, not the add-on config itslef.

Please try to reinstall and tell me how it goes

**Comment by danimtb** [comment]
Just release new versions 0.3.0 and built images for dasshio so it does not have to be build in the hass.io machine. Please update!"
