### ISSUE TITLE
install on home assistant ?

### ISSUE THREAD

**Issue by lam560** [danimtb/dasshio#41]
I have home assistant on my orange pi running Debian.
is it possible to install dasshio ?

thanks

**Comment by danimtb** [comment]
These are the architectures with prebuild images of dasshio: https://hub.docker.com/r/danimtb/

Give it a try and let me know! 😉

**Comment by danimtb** [comment]
Closing this in the meantime as this is not a Dasshio issue. Please report if you give it a try. Thanks! :)
