### ISSUE TITLE
Unable to perform  request (Dasshio)

### ISSUE THREAD

**Issue by saad1232** [danimtb/dasshio#46]
Can anyone help me with this please, this is driving me crazy, from few days i'm trying to solve it but i'm new to this stuff couldn't get it.

Thanks

![image](https://user-images.githubusercontent.com/25851398/43582272-97218a8c-9664-11e8-820c-052e1de55e5a.png)

**Comment by danimtb** [comment]
Try using:

"service": "toggle"

**Comment by mavericksv** [comment]
I am also having this same issue, and I changed it to Toggle as well.

The exact command works in the developer console, but I am getting the error above when it detects my button press.

    {
      "name": "Glad",
      "address": "MAC",
      "domain": "light",
      "service": "toggle",
      "service_data": "light.office_strip"

**Comment by mavericksv** [comment]
Just to show it's the same:

2018-08-05 15:28:20,000 | INFO | Request: http://hassio/homeassistant/api/services/light/light.toggle
2018-08-05 15:28:20,001 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 56, in arp_display
    button["service_data"]), headers={'x-ha-access': os.environ.get('HASSIO_TOKEN')})
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by danimtb** [comment]
Ok, now I got it.

Service data should be a json formatted string. Like this:

```
 "service_data": "{\"entity_id\": \"light.room_light\"}"
```

Please try that and close this issue if that's the solution. Many thanks!

**Comment by mavericksv** [comment]
Now it is this:
2018-08-05 18:31:33,623 | INFO | Request: http://hassio/homeassistant/api/services/light/toggle
2018-08-05 18:31:33,718 | INFO | Status Code: 502
2018-08-05 18:31:33,719 | ERROR | Bad request

{
  "timeout": 5,
  "buttons": [
    {
      "name": "Glad",
      "address": "68:37:E9:01:A1:52",
      "domain": "light",
      "service": "toggle",
      "service_data": "{\"xxxxxx09880446f29a832a8xxxxxxxxx\": \"light.office_strip\"}"
    }
  ]
}

**Comment by mavericksv** [comment]
Hmm, now it is this:

2018-08-05 18:31:33,622 | INFO | Glad button pressed!
2018-08-05 18:31:33,623 | INFO | Request: http://hassio/homeassistant/api/services/light/toggle
2018-08-05 18:31:33,718 | INFO | Status Code: 502
2018-08-05 18:31:33,719 | ERROR | Bad request

{
  "timeout": 5,
  "buttons": [
    {
      "name": "Glad",
      "address": "MAC",
      "domain": "light",
      "service": "toggle",
      "service_data": "{\"xxxxxx09880446f29a832a8xxxxxxxxx\": \"light.office_strip\"}"
    }
  ]
}

**Comment by saad1232** [comment]
I'm Done with it, Works Just fine now with the following setup
```
{
  "timeout": 20,
  "buttons": [
    {
      "name": "Cafe",
      "address": "KC:A6:67:96:7B:6A",
      "domain": "switch",
      "service": "toggle",
      "service_data": "{\"entity_id\": \"switch.office_lights\"}"
    }
  ]
}
```

**Comment by mavericksv** [comment]
Mine still does not work, even with this: 
```
{
  "timeout": 5,
  "buttons": [
    {
      "name": "Glad",
      "address": "MAC",
      "domain": "light",
      "service": "toggle",
      "service_data": "{\"entity_id\": \"light.office_strip\"}"
    }
  ]
}
```

**Comment by danimtb** [comment]
@mavericksv please check your configuration. @saad1232 reported it just worked.

Make sure you scape the quote symbols in service_data like this: ``\"``

https://github.com/danimtb/dasshio#options-example-domain-service-service_data
