### ISSUE TITLE
502 Bad request with HA v0.75.0

### ISSUE THREAD

**Issue by forast3r** [danimtb/dasshio#51]
I'm getting 502 errors again (since installing homeassistant v0.75):

2018-08-06 13:13:54,889 | INFO | button1 button pressed!
2018-08-06 13:13:54,889 | INFO | Request: http://hassio/homeassistant/api/services/automation/trigger
2018-08-06 13:13:54,933 | INFO | Status Code: 502
2018-08-06 13:13:54,934 | ERROR | Bad request
2018-08-06 13:13:54,950 | INFO | Packet captured, waiting 20s ...
2018-08-06 13:14:14,966 | INFO | Starting sniffing...

my config hasn't changed since HA v0.74.2, I think something has broken in the HA api auth system (again)
This is what I can see in the hassio log:

18-08-06 11:13:54 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/services/automation/trigger access from 03d23610_dasshio
18-08-06 11:13:54 ERROR (MainThread) [hassio.homeassistant] Authenticate problem with HomeAssistant!
18-08-06 11:13:54 ERROR (MainThread) [hassio.api.proxy] Authenticate error on API for request services/automation/trigger

**Comment by mavericksv** [comment]
Yep, same here, just like in the other thread that was marked as closed:

{
  "timeout": 5,
  "buttons": [
    {
      "name": "Glad",
      "address": "MAC",
      "domain": "light",
      "service": "toggle",
      "service_data": "{\"entity_id\": \"light.office_strip\"}"
    }
  ]
}

I am seeing both of the errors as above.

**Comment by BertrumUK** [comment]
Try changing your domain to this :-

"domain": "homeassistant”,

**Comment by forast3r** [comment]
Solved with latest update:

supervisor: 125
HA: 0.75.3

It is working again with domain: "automation" without specifying the complete url
Will reopen if it fails again
