### ISSUE TITLE
Authentification failure

### ISSUE THREAD

**Issue by v-marinkov** [danimtb/dasshio#52]
Hi, I am running the latest Hassio and HA 0.75.2. Dasshio captures the dash button packet but fails on the api request:
```
Request: http://hassio/homeassistant/api/services/script/ifttt.trigger
Status Code: 401
```
The logs of HA show
```
Login attempt or request with invalid authentication from 172.30.32.2
12:10 PM components/http/ban.py (WARNING)
```
Here's how my http component looks like in configuration.yaml:
```
http:
  api_password: !secret http_password
```
Am I missing something basic? Thanks!

**Comment by danimtb** [comment]
Could this be a duplicated of #51 ? If so, please close this issue an continue conversation there. Thanks!

**Comment by forast3r** [comment]
Check my latest comment https://github.com/danimtb/dasshio/issues/51
Does it work for you updating to 0.75.3 (and hassio supervisor 125)?

**Comment by danimtb** [comment]
Closing this as it seems it was solved. Feel free to comment or reopen if not. Thanks! :)
