### ISSUE TITLE
Manual installation (not as an add-on)

### ISSUE THREAD

**Issue by etatus** [danimtb/dasshio#54]
Hello,

I have intalled Home Assistant manually in a python environment and I'd like to integrate dasshio, but the only installation process described is as Hassio addon. Is it possible to install dasshio manually (not as an addon)?

Thanks!

**Comment by etatus** [comment]
Ok, I made it as follows (@danimtb maybe you want to include this instructions in README.md):

**Requirements:**
To have installed Home Assistant following this guide: https://www.home-assistant.io/docs/installation/virtualenv/

**1. Create the folder /srv/homeassistant/dasshio to store the files:**
```
/srv/homeassistant/dasshiodasshio.py
/srv/homeassistant/dasshiodata/config.json
/srv/homeassistant/dasshiodata/options.json
```
**2. In options.json define the url, headers, body and domain of your Home Assistant integration:**
```
{
  "server": "http://localhost:8123",
  "timeout": 30,
  "buttons": [
  {
    "name": "Duracell",
    "address": "xx:xx:xx:xx:xx:xx",
    "url": "http://localhost:8123/api/services/switch/toggle",
    "headers": "{\"x-ha-access\": \"ha_password\"}",
    "body": "{\"entity_id\":\"switch.socket_power\"}",
    "domain": "switch"
  }]
}
```
**3. To run dasshio as a service, create the file: /lib/systemd/system/dasshio.service**
```
[Unit]
Description=dasshio - Amazon Dash Buttons
After=network.target,home-assistant\@homeassistant.service
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/srv/homeassistant/bin/python3 /srv/homeassistant/dasshio/dasshio.py

[Install]
WantedBy=multi-user.target
```
**4. Manually start/stop the service:** 
```
sudo systemctl start dasshio
sudo systemctl status dasshio
sudo systemctl stop dasshio
```
**5. Automatically start the service on boot** 
```
sudo systemctl enable dasshio
```

**Comment by danimtb** [comment]
I think the pip install step is missing at the top. Anyway, thanks a lot for writing up the steps you folowed here.

I will try to incorporate them in the readme. However, if you want to contribute those steps to the readme yourself, they will be more than welcomed! =)

Thanks
