### ISSUE TITLE
Amend readme - add docker network to 

### ISSUE THREAD

**Issue by genestealer** [danimtb/dasshio#55]
May I suggest you add the following:
Note: Dasshio uses http://hassio/homeassistant/api/services/{domain}/{service} as the base url to route requests over the Hassio local network between the containers. This is the prefered method as it means the requests don't have to leave the machine Hassio is running on (See Hass.io Addon Communication).
**For those running [Hass.io in Docker ](https://www.home-assistant.io/hassio/installation/#alternative-install-on-generic-linux-server) you must add the docker internal IP address to HTTP trusted_networks in the configuration.yaml file.**

```
# Example configuration.yaml entry
http:
    trusted_networks:
    - 127.0.0.1
    - 192.168.0.0/24
    - 172.17.0.0/16 # Docker bridge
    - 172.30.32.0/23 # Docker hassio
```

**Comment by genestealer** [comment]
Alternatively, removing the "trusted_networks:" list means HASS automatically added it's own internal address to the list of trusted_networks, bypassing the issue

**Comment by danimtb** [comment]
Sure @Genestealer. Feel free to open a PR to the readme! Thanks 😄

**Comment by genestealer** [comment]
Done 👍

**Comment by danimtb** [comment]
Thanks @Genestealer !
