### ISSUE TITLE
service_data - how two set more than one setting

### ISSUE THREAD

**Issue by h4nc** [danimtb/dasshio#62]
I'd like to toggle my light, and when it turns on it should always turn on at a certain brightness value?

How do I have to set service_data for more than one setting?
`"service_data": "{\"entity_id\": \"light.trainingszimmer\"}"`

I tried this: 
`"service_data": "{\"entity_id\": \"light.trainingszimmer\"}, {\"brightness_pct\": \"50\"}"`

But this did not work, I dont know how to format it correct.

**Comment by h4nc** [comment]
anyone?

**Comment by danimtb** [comment]
hi @h4nc,

You only have to skip all the double quotes on the value except the staring and ending ones. Also maintain the JSON format. Like this:

```
"service_data": "{\"entity_id\": \"light.trainingszimmer\", \"brightness_pct\": \"50\"}"
```

Give it a try and don't forget to close this issue if it worked. Thanks!

**Comment by h4nc** [comment]
Unfortunately this only works with "turn_on" and not with "toggle".

Is there a way to use toggle and brightness?

**Comment by danimtb** [comment]
I guess toggle will not work as setting a brightness when you are actually turning off makes no sense. However, you can trigger a script with dasshio that makes the logic for you:

script steps:

1.- toggle light (without brightness)
2.- Condition: if light is on
3.- Set light brightness

I am closing this as it is not a problem of dasshio. Thanks!
