### ISSUE TITLE
Crashes hassio on rpi3b+ runinig 0.84.3

### ISSUE THREAD

**Issue by critterskins** [danimtb/dasshio#66]
Works for about 2 min of testing then Home assistant crashes just keeps trying to reconnect but wont I set it not to start on boot so i pull the power and try again with same issue. Nothing in Home Assistant log to reference. Using this image https://www.home-assistant.io/hassio/installation/ for 32bit

**Comment by MrSeanRoss** [comment]
I'm having the same problem on 0.88.1.

**Comment by danimtb** [comment]
Sorry for answering too late. If this is still an issue in new home assistant versions please open a new issue with the version you are using. Thanks!
