### ISSUE TITLE
Hass.io crashes when attempting to install

### ISSUE THREAD

**Issue by MiralDesai** [danimtb/dasshio#68]
Hass.io installed on Pi (HassOS 1.13)
Home assistant 0.86.2
hass.io supervisor 143

Trying to install the add on after adding the repo but within seconds the entire system crashes and reboots.  Can't see anything in the logs because it crashes then reboots with fresh logs, anyone else getting this?

The last thing spotted in the logs was that the SyncWorker was attempting to pull data from this repo.

Last log: `19-02-13 22:28:57 INFO (SyncWorker_8) [hassio.docker.interface] Pull image danimtb/armhf-dasshio tag 0.3.1.`

**Comment by MiralDesai** [comment]
Turns out this was because my device wasn't getting enough power. Changed the power brick and it's all good now.

**Comment by danimtb** [comment]
Thanks for reporting and glad you solved the issue 😄
