### ISSUE TITLE
"arch" must be specified in config.json

### ISSUE THREAD

**Issue by forast3r** [danimtb/dasshio#71]
Latest breaking changes require that "arch" is specified in config.json

This issue is also referenced here: https://github.com/home-assistant/home-assistant/issues/22854

**Comment by forast3r** [comment]
Meanwhile i made a fork with hard-coded "arch" to "amd64" but I guess there's a more elegant solution

**Comment by vincegre** [comment]
> Meanwhile i made a fork with hard-coded "arch" to "amd64" but I guess there's a more elegant solution

Would you mind to share the archive ? or link if it's on github so others can enjoy it ? as it look that owner of that repository is completely away or overbusy to handle any issues on that program since a while !

**Comment by forast3r** [comment]
> > Meanwhile i made a fork with hard-coded "arch" to "amd64" but I guess there's a more elegant solution
> 
> Would you mind to share the archive ? or link if it's on github so others can enjoy it ? as it look that owner of that repository is completely away or overbusy to handle any issues on that program since a while !

Sure, it's in the fork I made: https://github.com/forast3r/dasshio

PS no warranties :)

**Comment by vincegre** [comment]
Thanks and in fact I figured out too the solution by myself ;) will share it on the other bug thread if you don't mind ;)

**Comment by lucacorn77** [comment]
Hi everyone, I created a fork and added arch I specified "arch" in configuration.json inserting armv7, now the front sees the addon but when I try to install it it gives me error

**Comment by lucacorn77** [comment]
I changed arch from armv7 to armhf.  now it installs and it works. Thank you so much!

**Comment by giuscond** [comment]
Thank you so much for the fork!

**Comment by danimtb** [comment]
Fixed in #73
