### ISSUE TITLE
 Repository not found by Hass.io

### ISSUE THREAD

**Issue by LucaBopf** [danimtb/dasshio#72]
When i add the repo to my add-on-store, nothing happen.
In the system tab i get this errors:
19-04-09 18:45:38 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/danimtb/ repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/danimtb/ /data/addons/git/4fae26c1
  stderr: 'Cloning into '/data/addons/git/4fae26c1'...
remote: Not Found
fatal: repository 'https://github.com/danimtb/' not found
'.
19-04-09 18:45:38 ERROR (MainThread) [hassio.addons] Can't load from repository https://github.com/danimtb/

**Comment by giuscond** [comment]
I have the same problem in a PC with Ubuntu Desktop 19 that running Home Assistant. Do you found any solutions?

**Comment by danimtb** [comment]
Should be fixed by #74
