### ISSUE TITLE
Manifest Error in 0.3.4

### ISSUE THREAD

**Issue by lubeda** [danimtb/dasshio#80]
19-04-15 16:17:31 ERROR (SyncWorker_11) [hassio.docker.interface] Can't install danimtb/amd64-dasshio:0.3.4 -> 404 Client Error: Not Found ("manifest for danimtb/amd64-dasshio:0.3.4 not found").

**Comment by dustardly** [comment]
same problem ;( unlucky day today ! Dasshio don't want  work :P

**Comment by lubeda** [comment]
Solved by waiting, seems ther was some replication delay
