### ISSUE TITLE
dash button don't working no more?

### ISSUE THREAD

**Issue by dustardly** [danimtb/dasshio#92]
there is a solution , my dash buttons on 0.99.2 version of HA not more working.

Is Amazon dismissed? it's possible to use it in any way again?

AWS IoT Button  II version can work and if is possible there is a guide? 

Thanks.

**Comment by rourke750** [comment]
I am also getting the same issue, I believe the problem might be hassio and not this.  Have you managed to maybe fix it by now?

**Comment by danimtb** [comment]
I am no longer able to pair new buttons with the Amazon app here in europe. This might be the main issue
