### ISSUE TITLE
Amazon Dash button Not working updating Home Assistant 0.102.2

### ISSUE THREAD

**Issue by ceaswaran** [danimtb/dasshio#95]
Hi,
Suddenly I observe my Dash button Not working after updating Home Assistant 0.102.2
My Dasshio version is 0.3.8
My Dasshio Home Assitant Config is as follows:

```
{
  "timeout": 20,
  "buttons": [
    {
      "name": "Gillette",
      "address": "XX:E1:XX:XX:XX:XX",
      "domain": "switch",
      "service": "toggle",
      "service_data": "{\"entity_id\": \"switch.all_light\"}"
    }
  ]
}
```
I dont see my Light toggle?
I see Amazon button connecting to wifi (bluelight)
Please help to resolve

**Comment by JesCR** [comment]
Hi.
I think that this is not working anymore. My two dash buttons stop working too.

**Comment by danimtb** [comment]
Hi!

I have not updated to the latest version of home assistant yet but I don't think it is related to that. My bet is in the line of @JesCR comment and probably Amazon servers are making the button disconnect as they have discontinued physical buttons.

However, I think connecting the button like via this method https://github.com/danimtb/dasshio#how-to-connect-your-dash-button-to-your-wifi and then banning internet access to the button in your router would prevent the button from disconnecting.

**Comment by ceaswaran** [comment]
> Hi!
> 
> I have not updated to the latest version of home assistant yet but I don't think it is related to that. My bet is in the line of @JesCR comment and probably Amazon servers are making the button disconnect as they have discontinued physical buttons.
> 
> However, I think connecting the button like via this method https://github.com/danimtb/dasshio#how-to-connect-your-dash-button-to-your-wifi and then banning internet access to the button in your router would prevent the button from disconnecting.

One point to be noted is after trying this wifi connection method https://github.com/danimtb/dasshio#how-to-connect-your-dash-button-to-your-wifi 
I dont see the mac address of my Amazon dash listed by my router as connected device. (Fing app)

**Comment by danimtb** [comment]
The button only connects to the wifi during 10 seconds or so when you press the button

**Comment by 0rn0lf** [comment]
@ceaswaran depending on your router you could check the DHCP lease table. It should show all IP's used in the last days
