### ISSUE TITLE
Format for button connection to wifi

### ISSUE THREAD

**Issue by theaddies** [danimtb/dasshio#96]
Sorry for the simple question.  I am confused about the syntax for the line below.
`http://192.168.0.1/?amzn_ssid=<SSID>&amzn_pw=<PASSWORD>`
Do I enter <SSID>, 'SSID', SSID or another combination?  In other words do I include the "<>" characters or not and do I need any additional characters like ' or ".

**Comment by danimtb** [comment]
Don't worry, questions are always welcome.

Just replace `<SSDI>` with your wifi network name and `<PASSWORD>` with your wifi network password. I'd suggest you to use the 2.4 GHz Wifi as AFAIK Amazon Dash Button's do not see the new 5 GHz ones

**Comment by theaddies** [comment]
Thanks.

**Comment by danimtb** [comment]
Did that work? Can the issue be closed as solved? thanks

**Comment by mdframe** [comment]
Can I use this same thread as I am unable to use the URL provide to update my Dash button?  It does the activities of immediately disconnecting and then I press the button again and the light is a solid blue however it does not seem to attach my network as I do not see it in my router MAC list.    Any other ideas?  I have done the URL many times.

**Comment by nickg90** [comment]
same for me. I can see it in config mode, get the MAD address etc, I type in address with WIFI SSID and PW and it disconnects immediatly. but following that, it dosnt seem to connect and the DASSHIO logs dont see anything. I tried looking for it on my wifi connections but it dosnt seem to appear

**Comment by anatwick** [comment]
did you guys ever figure this out?  I'm unable to get any of the ones i have connected. I can see the mac address by connecting to that devices wifi and going to 192.168.0.1 but when i enter the URL for the password and network it doesnt appear to actually connect to my network

**Comment by danimtb** [comment]
closing as solved as the original issue was addressed. If there are other issues, please open a new ticket. thank you 😄
